export type Language = "en" | "si" | "ta";

export const translations = {
    landing: {
        en: {
            appTitle: "CassavaAI",
            tagline: "Smart Cassava Farming with AI",
            description:
                "Detect diseases early and predict yields accurately with our AI-powered tools designed for Sri Lankan farmers.",
            diseaseDetection: "Disease Detection",
            diseaseDesc: "Upload photos to identify cassava diseases instantly",
            yieldPrediction: "Yield Prediction",
            yieldDesc: "Predict your harvest yield with AI analysis",
            getStarted: "Get Started",
            learnMore: "Learn More",
        },
        si: {
            appTitle: "කැසාවා AI",
            tagline: "AI සමඟ බුද්ධිමත් කැසාවා වගාව",
            description: "ශ්‍රී ලංකා ගොවීන් සඳහා නිර්මාණය කරන ලද අපගේ AI මෙවලම් සමඟ රෝග ඉක්මනින් හඳුනාගෙන අස්වැන්න නිවැරදිව පුරෝකථනය කරන්න.",
            diseaseDetection: "රෝග හඳුනාගැනීම",
            diseaseDesc: "කැසාවා රෝග ක්ෂණිකව හඳුනාගැනීමට ඡායාරූප උඩුගත කරන්න",
            yieldPrediction: "අස්වැන්න පුරෝකථනය",
            yieldDesc: "AI විශ්ලේෂණය සමඟ ඔබේ අස්වැන්න පුරෝකථනය කරන්න",
            getStarted: "ආරම්භ කරන්න",
            learnMore: "තව දැනගන්න",
        },
        ta: {
            appTitle: "கசாவா AI",
            tagline: "AI உடன் புத்திசாலித்தனமான கசாவா விவசாயம்",
            description: "இலங்கை விவசாயிகளுக்காக வடிவமைக்கப்பட்ட எங்கள் AI கருவிகளுடன் நோய்களை விரைவில் கண்டறிந்து மகசூலை துல்லியமாக கணிக்கவும்.",
            diseaseDetection: "நோய் கண்டறிதல்",
            diseaseDesc: "கசாவா நோய்களை உடனடியாக அடையாளம் காண புகைப்படங்களை பதிவேற்றவும்",
            yieldPrediction: "மகசூல் கணிப்பு",
            yieldDesc: "AI பகுப்பாய்வுடன் உங்கள் அறுவடை மகசூலை கணிக்கவும்",
            getStarted: "தொடங்குங்கள்",
            learnMore: "மேலும் அறிக",
        },
    },
    disease: {
        en: {
            title: "Cassava Disease Detection",
            subtitle: "Upload a photo of your cassava leaf for AI-powered disease analysis",
            instructions: [
                "Take a clear photo of a single cassava leaf",
                "Ensure good lighting and focus",
                "Include the entire leaf in the frame",
                "Avoid shadows and blurry images",
            ],
            uploadArea: "Click to upload or drag and drop",
            supportedFormats: "Supported formats: JPG, PNG, WEBP (Max 10MB)",
            uploadButton: "Analyze Leaf",
            photoTips: "Photo Tips",
            tipsContent: [
                "Use natural daylight when possible",
                "Hold the camera steady to avoid blur",
                "Fill the frame with the leaf",
                "Avoid shadows covering the leaf",
                "Clean the leaf surface if dusty",
            ],
            uploading: "Analyzing...",
            selectFile: "Select Image File",
            fileSelected: "File selected successfully",
            backToHome: "Back to Home",
        },
        si: {
            title: "කැසාවා රෝග හඳුනාගැනීම",
            subtitle: "AI මගින් රෝග විශ්ලේෂණය සඳහා ඔබේ කැසාවා කොළයේ ඡායාරූපයක් උඩුගත කරන්න",
            instructions: [
                "තනි කැසාවා කොළයක පැහැදිලි ඡායාරූපයක් ගන්න",
                "හොඳ ආලෝකය සහ නාභිගත කිරීම සහතික කරන්න",
                "සම්පූර්ණ කොළය රාමුව තුළ ඇතුළත් කරන්න",
                "සෙවණැලි සහ බොඳ රූප වළක්වන්න",
            ],
            uploadArea: "උඩුගත කිරීමට ක්ලික් කරන්න හෝ ඇදගෙන දමන්න",
            supportedFormats: "සහාය දක්වන ආකෘති: JPG, PNG, WEBP (උපරිම 10MB)",
            uploadButton: "කොළය විශ්ලේෂණය කරන්න",
            photoTips: "ඡායාරූප ඉඟි",
            tipsContent: [
                "හැකි විට ස්වභාවික දිවා ආලෝකය භාවිතා කරන්න",
                "බොඳ වීම වළක්වා ගැනීමට කැමරාව ස්ථිරව අල්ලා ගන්න",
                "කොළය සමඟ රාමුව පුරවන්න",
                "කොළය ආවරණය කරන සෙවණැලි වළක්වන්න",
                "දූවිලි නම් කොළ මතුපිට පිරිසිදු කරන්න",
            ],
            uploading: "විශ්ලේෂණය කරමින්...",
            selectFile: "රූප ගොනුව තෝරන්න",
            fileSelected: "ගොනුව සාර්ථකව තෝරා ගන්නා ලදී",
            backToHome: "මුල් පිටුවට",
        },
        ta: {
            title: "கசாவா நோய் கண்டறிதல்",
            subtitle: "AI மூலம் நோய் பகுப்பாய்வுக்காக உங்கள் கசாவா இலையின் புகைப்படத்தை பதிவேற்றவும்",
            instructions: [
                "ஒரு கசாவா இலையின் தெளிவான புகைப்படத்தை எடுக்கவும்",
                "நல்ல வெளிச்சம் மற்றும் கவனம் செலுத்துவதை உறுதி செய்யவும்",
                "முழு இலையையும் சட்டகத்தில் சேர்க்கவும்",
                "நிழல்கள் மற்றும் மங்கலான படங்களை தவிர்க்கவும்",
            ],
            uploadArea: "பதிவேற்ற கிளிக் செய்யவும் அல்லது இழுத்து விடவும்",
            supportedFormats: "ஆதரிக்கப்படும் வடிவங்கள்: JPG, PNG, WEBP (அதிகபட்சம் 10MB)",
            uploadButton: "இலையை பகுப்பாய்வு செய்ய���ும்",
            photoTips: "புகைப்பட குறிப்புகள்",
            tipsContent: [
                "முடிந்தால் இயற்கை பகல் வெளிச்சத்தை பயன்படுத்தவும்",
                "மங்கலானதை தவிர்க்க கேமராவை நிலையாக பிடிக்கவும்",
                "இலையுடன் சட்டகத்தை நிரப்பவும்",
                "இலையை மறைக்கும் நிழல்களை தவிர்க்கவும்",
                "தூசி இருந்தால் இலை மேற்பரப்பை சுத்தம் செய்யவும்",
            ],
            uploading: "பகுப்பாய்வு செய்கிறது...",
            selectFile: "படக் கோப்பைத் தேர்ந்தெடுக்கவும்",
            fileSelected: "கோப்பு வெற்றிகரமாக தேர்ந்தெடுக்கப்பட்டது",
            backToHome: "முகப்புக்கு",
        },
    },
    yeild: {
        en: {
            title: "Cassava Yield Prediction",
            subtitle: "Enter your plant measurements to get an AI-powered yield prediction",
            plantMetrics: "Plant Measurements",
            environmentalFactors: "Environmental Factors",
            farmingPractices: "Farming Practices",

            // Form fields
            plantHeight: "Plant Height",
            plantHeightDesc: "Measure from soil level to the top of the main stem",
            stemDiameter: "Stem Diameter",
            stemDiameterDesc: "Measure the thickness of the main stem at 30cm from ground",
            leafCount: "Active Leaf Count",
            leafCountDesc: "Count only healthy, fully developed leaves",
            plantAge: "Plant Age",
            plantAgeDesc: "Number of months since planting",
            soilMoisture: "Soil Moisture Level",
            soilMoistureDesc: "Current soil moisture condition",
            temperature: "Average Temperature",
            temperatureDesc: "Average daily temperature in your area",
            fertilizer: "Fertilizer Application",
            fertilizerDesc: "Type and frequency of fertilizer used",
            plantingDensity: "Planting Density",
            plantingDensityDesc: "Number of plants per hectare",
            variety: "Cassava Variety",
            varietyDesc: "Select the cassava variety you are growing",

            // Options
            moistureLevels: {
                low: "Low (Dry soil)",
                medium: "Medium (Moist soil)",
                high: "High (Wet soil)",
            },
            fertilizerTypes: {
                none: "No fertilizer",
                organic: "Organic fertilizer",
                chemical: "Chemical fertilizer",
                mixed: "Mixed (Organic + Chemical)",
            },
            varieties: {
                local: "Local variety",
                improved: "Improved variety",
                hybrid: "Hybrid variety",
            },

            // Units
            cm: "cm",
            months: "months",
            celsius: "°C",
            plantsPerHectare: "plants/hectare",

            // Buttons
            predictYield: "Predict Yield",
            predicting: "Predicting...",
            reset: "Reset Form",
            backToHome: "Back to Home",

            // Validation
            required: "This field is required",
            invalidNumber: "Please enter a valid number",
        },
        si: {
            title: "කැසාවා අස්වැන්න පුරෝකථනය",
            subtitle: "AI මගින් අස්වැන්න පුරෝකථනය ලබා ගැනීමට ඔබේ ශාක මිනුම් ඇතුළත් කරන්න",
            plantMetrics: "ශාක මිනුම්",
            environmentalFactors: "පරිසර සාධක",
            farmingPractices: "ගොවිතැන් ක්‍රම",

            plantHeight: "ශාක උස",
            plantHeightDesc: "පස් මට්ටමේ සිට ප්‍රධාන කඳේ මුදුන දක්වා මනින්න",
            stemDiameter: "කඳ විෂ්කම්භය",
            stemDiameterDesc: "බිමේ සිට සෙ.මී. 30ක් උසින් ප���‍රධාන කඳේ ඝනකම මනින්න",
            leafCount: "ක්‍රියාකාරී කොළ ගණන",
            leafCountDesc: "සෞඛ්‍ය සම්පන්න, සම්පූර්ණයෙන් වර්ධනය වූ කොළ පමණක් ගණන් කරන්න",
            plantAge: "ශාක වයස",
            plantAgeDesc: "රෝපණය කළ දින සිට මාස ගණන",
            soilMoisture: "පස් තෙතමනය",
            soilMoistureDesc: "වර්තමාන පස් තෙතමනයේ තත්ත්වය",
            temperature: "සාමාන්‍ය උෂ්ණත්වය",
            temperatureDesc: "ඔබේ ප්‍රදේශයේ සාමාන්‍ය දෛනික උෂ්ණත්වය",
            fertilizer: "පොහොර යෙදීම",
            fertilizerDesc: "භාවිතා කරන පොහොර වර්ගය සහ වාර ගණන",
            plantingDensity: "රෝපණ ඝනත්වය",
            plantingDensityDesc: "හෙක්ටයරයකට ශාක ගණන",
            variety: "කැසාවා ප්‍රභේදය",
            varietyDesc: "ඔබ වගා කරන කැසාවා ප්‍රභේදය තෝරන්න",

            moistureLevels: {
                low: "අඩු (වියළි පස)",
                medium: "මධ්‍යම (තෙත් පස)",
                high: "ඉහළ (තෙත් පස)",
            },
            fertilizerTypes: {
                none: "පොහොර නැත",
                organic: "කාබනික පොහොර",
                chemical: "රසායනික පොහොර",
                mixed: "මිශ්‍ර (කාබනික + රසායනික)",
            },
            varieties: {
                local: "දේශීය ප්‍රභේදය",
                improved: "වැඩිදියුණු කළ ප්‍රභේදය",
                hybrid: "දෙමුහුන් ප්‍රභේදය",
            },

            cm: "සෙ.මී.",
            months: "මාස",
            celsius: "°C",
            plantsPerHectare: "ශාක/හෙක්ටයර",

            predictYield: "අස්වැන්න පුරෝකථනය කරන්න",
            predicting: "පුරෝකථනය කරමින්...",
            reset: "ආකෘතිය නැවත සකසන්න",
            backToHome: "මුල් පිටුවට",

            required: "මෙම ක්ෂේත්‍රය අවශ්‍යයි",
            invalidNumber: "කරුණාකර වලංගු අංකයක් ඇතුළත් කරන්න",
        },
        ta: {
            title: "கசாவா மகசூல் கணிப்பு",
            subtitle: "AI மூலம் மகசூல் கணிப்பு பெற உங்கள் தாவர அளவீடுகளை உள்ளிடவும்",
            plantMetrics: "தாவர அளவீடுகள்",
            environmentalFactors: "சுற்றுச்சூழல் காரணிகள்",
            farmingPractices: "விவசாய முறைகள்",

            plantHeight: "தாவர உயரம்",
            plantHeightDesc: "மண் மட்டத்திலிருந்து முக்கிய தண்டின் மேல் வரை அளவிடவும்",
            stemDiameter: "தண்டு விட்டம்",
            stemDiameterDesc: "தரையிலிருந்து 30 செ.மீ. உயரத்தில் முக்கிய தண்டின் தடிமனை அளவிடவும்",
            leafCount: "செயலில் உள்ள இலை எண்ணிக்கை",
            leafCountDesc: "ஆரோக்கியமான, முழுமையாக வளர்ந்த இலைகளை மட்டும் எண்ணவும்",
            plantAge: "தாவர வயது",
            plantAgeDesc: "நடவு செய்த நாளிலிருந்து மாதங்களின் எண்ணிக்கை",
            soilMoisture: "மண் ஈரப்பதம்",
            soilMoistureDesc: "தற்போதைய மண் ஈரப்பத நிலை",
            temperature: "சராசரி வெப்பநிலை",
            temperatureDesc: "உங்கள் பகுதியின் சராசரி தினசரி வெப்பநிலை",
            fertilizer: "உர பயன்பாடு",
            fertilizerDesc: "பயன்படுத்தும் உரத்தின் வகை மற்றும் அதிர்வெண்",
            plantingDensity: "நடவு அடர்த்தி",
            plantingDensityDesc: "ஹெக்டேருக்கு தாவரங்களின் எண்ணிக்கை",
            variety: "கசாவா வகை",
            varietyDesc: "நீங்கள் வளர்க்கும் கசாவா வகையை தேர்ந்தெடுக்கவும்",

            moistureLevels: {
                low: "குறைவு (வறண்ட மண்)",
                medium: "நடுத்தர (ஈரமான மண்)",
                high: "அதிக (ஈரமான மண்)",
            },
            fertilizerTypes: {
                none: "உரம் இல்லை",
                organic: "இயற்கை உரம்",
                chemical: "இரசாயன உரம்",
                mixed: "கலப்பு (இயற்கை + இரசாயன)",
            },
            varieties: {
                local: "உள்ளூர் வகை",
                improved: "மேம்படுத்தப்பட்ட வகை",
                hybrid: "கலப்பின வகை",
            },

            cm: "செ.மீ.",
            months: "மாதங்கள்",
            celsius: "°C",
            plantsPerHectare: "தாவரங்கள்/ஹெக்டேர்",

            predictYield: "மகசூலை கணிக்கவும்",
            predicting: "கணிக்கிறது...",
            reset: "படிவத்தை மீட்டமைக்கவும்",
            backToHome: "முகப்புக்கு",

            required: "இந்த புலம் தேவை",
            invalidNumber: "தயவுசெய்து சரியான எண்ணை உள்ளிடவும்",
        },
    },
};

export const languageNames = {
    en: "English",
    si: "සිංහල",
    ta: "தமிழ்",
};