export type Language = "en" | "si" | "ta";

export const translations = {
    landing: {
        en: {
            appTitle: "CassavaAI",
            tagline: "Smart Cassava Farming with AI",
            description:
                "Detect diseases early and predict yields accurately with our AI-powered tools designed for Sri Lankan farmers.",
            diseaseDetection: "Disease Detection",
            diseaseDesc: "Upload photos to identify cassava diseases instantly",
            yieldPrediction: "Yield Prediction",
            yieldDesc: "Predict your harvest yield with AI analysis",
            getStarted: "Get Started",
            learnMore: "Learn More",
        },
        si: {
            appTitle: "කැසාවා AI",
            tagline: "AI සමඟ බුද්ධිමත් කැසාවා වගාව",
            description: "ශ්‍රී ලංකා ගොවීන් සඳහා නිර්මාණය කරන ලද අපගේ AI මෙවලම් සමඟ රෝග ඉක්මනින් හඳුනාගෙන අස්වැන්න නිවැරදිව පුරෝකථනය කරන්න.",
            diseaseDetection: "රෝග හඳුනාගැනීම",
            diseaseDesc: "කැසාවා රෝග ක්ෂණිකව හඳුනාගැනීමට ඡායාරූප උඩුගත කරන්න",
            yieldPrediction: "අස්වැන්න පුරෝකථනය",
            yieldDesc: "AI විශ්ලේෂණය සමඟ ඔබේ අස්වැන්න පුරෝකථනය කරන්න",
            getStarted: "ආරම්භ කරන්න",
            learnMore: "තව දැනගන්න",
        },
        ta: {
            appTitle: "கசாவா AI",
            tagline: "AI உடன் புத்திசாலித்தனமான கசாவா விவசாயம்",
            description: "இலங்கை விவசாயிகளுக்காக வடிவமைக்கப்பட்ட எங்கள் AI கருவிகளுடன் நோய்களை விரைவில் கண்டறிந்து மகசூலை துல்லியமாக கணிக்கவும்.",
            diseaseDetection: "நோய் கண்டறிதல்",
            diseaseDesc: "கசாவா நோய்களை உடனடியாக அடையாளம் காண புகைப்படங்களை பதிவேற்றவும்",
            yieldPrediction: "மகசூல் கணிப்பு",
            yieldDesc: "AI பகுப்பாய்வுடன் உங்கள் அறுவடை மகசூலை கணிக்கவும்",
            getStarted: "தொடங்குங்கள்",
            learnMore: "மேலும் அறிக",
        },
    },
    disease: {
        en: {
            title: "Cassava Disease Detection",
            subtitle: "Upload a photo of your cassava leaf for AI-powered disease analysis",
            instructions: [
                "Take a clear photo of a single cassava leaf",
                "Ensure good lighting and focus",
                "Include the entire leaf in the frame",
                "Avoid shadows and blurry images",
            ],
            uploadArea: "Click to upload or drag and drop",
            supportedFormats: "Supported formats: JPG, PNG, WEBP (Max 10MB)",
            uploadButton: "Analyze Leaf",
            photoTips: "Photo Tips",
            tipsContent: [
                "Use natural daylight when possible",
                "Hold the camera steady to avoid blur",
                "Fill the frame with the leaf",
                "Avoid shadows covering the leaf",
                "Clean the leaf surface if dusty",
            ],
            uploading: "Analyzing...",
            selectFile: "Select Image File",
            fileSelected: "File selected successfully",
            backToHome: "Back to Home",
        },
        si: {
            title: "කැසාවා රෝග හඳුනාගැනීම",
            subtitle: "AI මගින් රෝග විශ්ලේෂණය සඳහා ඔබේ කැසාවා කොළයේ ඡායාරූපයක් උඩුගත කරන්න",
            instructions: [
                "තනි කැසාවා කොළයක පැහැදිලි ඡායාරූපයක් ගන්න",
                "හොඳ ආලෝකය සහ නාභිගත කිරීම සහතික කරන්න",
                "සම්පූර්ණ කොළය රාමුව තුළ ඇතුළත් කරන්න",
                "සෙවණැලි සහ බොඳ රූප වළක්වන්න",
            ],
            uploadArea: "උඩුගත කිරීමට ක්ලික් කරන්න හෝ ඇදගෙන දමන්න",
            supportedFormats: "සහාය දක්වන ආකෘති: JPG, PNG, WEBP (උපරිම 10MB)",
            uploadButton: "කොළය විශ්ලේෂණය කරන්න",
            photoTips: "ඡායාරූප ඉඟි",
            tipsContent: [
                "හැකි විට ස්වභාවික දිවා ආලෝකය භාවිතා කරන්න",
                "බොඳ වීම වළක්වා ගැනීමට කැමරාව ස්ථිරව අල්ලා ගන්න",
                "කොළය සමඟ රාමුව පුරවන්න",
                "කොළය ආවරණය කරන සෙවණැලි වළක්වන්න",
                "දූවිලි නම් කොළ මතුපිට පිරිසිදු කරන්න",
            ],
            uploading: "විශ්ලේෂණය කරමින්...",
            selectFile: "රූප ගොනුව තෝරන්න",
            fileSelected: "ගොනුව සාර්ථකව තෝරා ගන්නා ලදී",
            backToHome: "මුල් පිටුවට",
        },
        ta: {
            title: "கசாவா நோய் கண்டறிதல்",
            subtitle: "AI மூலம் நோய் பகுப்பாய்வுக்காக உங்கள் கசாவா இலையின் புகைப்படத்தை பதிவேற்றவும்",
            instructions: [
                "ஒரு கசாவா இலையின் தெளிவான புகைப்படத்தை எடுக்கவும்",
                "நல்ல வெளிச்சம் மற்றும் கவனம் செலுத்துவதை உறுதி செய்யவும்",
                "முழு இலையையும் சட்டகத்தில் சேர்க்கவும்",
                "நிழல்கள் மற்றும் மங்கலான படங்களை தவிர்க்கவும்",
            ],
            uploadArea: "பதிவேற்ற கிளிக் செய்யவும் அல்லது இழுத்து விடவும்",
            supportedFormats: "ஆதரிக்கப்படும் வடிவங்கள்: JPG, PNG, WEBP (அதிகபட்சம் 10MB)",
            uploadButton: "இலையை பகுப்பாய்வு செய்ய���ும்",
            photoTips: "புகைப்பட குறிப்புகள்",
            tipsContent: [
                "முடிந்தால் இயற்கை பகல் வெளிச்சத்தை பயன்படுத்தவும்",
                "மங்கலானதை தவிர்க்க கேமராவை நிலையாக பிடிக்கவும்",
                "இலையுடன் சட்டகத்தை நிரப்பவும்",
                "இலையை மறைக்கும் நிழல்களை தவிர்க்கவும்",
                "தூசி இருந்தால் இலை மேற்பரப்பை சுத்தம் செய்யவும்",
            ],
            uploading: "பகுப்பாய்வு செய்கிறது...",
            selectFile: "படக் கோப்பைத் தேர்ந்தெடுக்கவும்",
            fileSelected: "கோப்பு வெற்றிகரமாக தேர்ந்தெடுக்கப்பட்டது",
            backToHome: "முகப்புக்கு",
        },
    }
};

export const languageNames = {
    en: "English",
    si: "සිංහල",
    ta: "தமிழ்",
};